name: iOS workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, test and send code coverage
    runs-on: macos-latest

    steps:
      - name: Xcode version
        run: xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build and test
        run: xcodebuild -scheme Prontalize -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13 Pro" -enableCodeCoverage YES -resultBundlePath coverage/result.xcresult build test
      
      - name: Convert code coverage
        run: xcrun xccov view --report --json coverage/result.xcresult > coverage.json

      - name: xccov2lcov
        run: |
          git clone https://github.com/trax-retail/xccov2lcov.git xccov2lcov
          (cd xccov2lcov; swift run xccov2lcov ../coverage.json > ../lcov.info)

      - name: Code Coverage
        run: |
          set -o pipefail
          export PATH="/usr/local/opt/curl/bin:$PATH"
          curl --version
          bash <(curl -s https://codecov.io/bash) -J '^Prontalize$' -F ios
