name: iOS workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  BuildAndTest:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Derived Data
        run: mkdir -p DerivedData
        
      - name: Install Xcpretty
        run: gem install xcpretty --no-document --quiet
        
      - name: Build
        run: |
          set -o pipefail
          xcodebuild -scheme Prontalize -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13 Pro" -enableCodeCoverage YES -derivedDataPath ./DerivedData build test | xcpretty -c
          
      - name: Code Coverage
        run: |
          set -o pipefail
          export PATH="/usr/local/opt/curl/bin:$PATH"
          curl --version
          bash <(curl -s https://codecov.io/bash) -D './DerivedData' -J '^Prontalize$' -c -X gcov -F ios
